global:
  scrape_interval: 15s # default is 1 minute

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: caddy
    static_configs:
      - targets: ['caddy:2019']

  - job_name: node_exporter
    static_configs:
      - targets: ['node_exporter:9100']