global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: caddy
    static_configs:
      - targets: ['caddy:2019']

  - job_name: node_exporter
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: ntfy
    static_configs:
      - targets: ['ntfy:8080']
